definitions:
  models.Instagram:
    properties:
      createdAt:
        type: string
      followers:
        type: string
      following:
        type: string
      id:
        type: integer
      likes:
        type: string
      postCount:
        type: string
      profile:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  models.Tiktok:
    properties:
      createdAt:
        type: string
      followers:
        type: string
      following:
        type: string
      id:
        type: integer
      likes:
        type: string
      postCount:
        type: string
      profile:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for a claimd API.
  title: Claimd API
  version: 1.0.0
paths:
  /instagram:
    get:
      description: Retrieve all the Instagram data from the database
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Instagram'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetInstagramData
  /scrape:
    get:
      description: Scrape all platforms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ScrapePlatform
  /tiktok:
    get:
      description: Retrieve all the Tiktok data from the database
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tiktok'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetTiktokData
swagger: "2.0"
